// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrhwugiqwuzojtdttwft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyaHd1Z2lxd3V6b2p0ZHR0d2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzA5ODgsImV4cCI6MjA3MTk0Njk4OH0.XoqzqQgjy5uarKkrj13LUB6Wfnv1GV-pGASm2g8J-ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});